---
title: "HW5"
author: "SDS348 Fall 2019"
date: "10/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preethi Keerthipati pk7932

**This homework is due on Oct 6, 2019 at 11:59pm. Please submit as a pdf file on Canvas.**

*For all questions, include the R commands/functions that you used to find your answer. Answers without supporting code will not receive credit.*

> ### How to submit this assignment
>All homework assignments will be completed using R Markdown. These `.Rmd` files consist of >text/syntax (formatted using Markdown) alongside embedded R code. 
>When you have completed the assignment (by adding R code inside codeblocks and supporting text outside of the codeblocks), create your document as follows:

> - Click the "Knit" button (above) to create an .html file
> - Open the html file in your internet browser to view
> - Go to `File > Print` and print your .html file to a .pdf
> - (or knit to PDF)
> - Upload the .pdf file to Canvas

---

### Question 1:

##### WARNING: In this assignment, you will be performing computationally expensive operations on large data files. If the server gets slow, try it on a different one (educomp01, educomp02, educomp03, or educomp04) or try using a local computer. You are advised to begin working on this well before the due date. IF YOUR COMPUTER IS RUNNING SLOWLY when trying to figure out the reshape, YOU ARE STRONGLY ENCOURAGED to take a subset of the wide merged data (e.g., first 500 rows) and test your code on that. Once you get everything working, replace your test sample with the entire dataset and run it one final time (it will likely take several minutes to knit the entire assignment: I would allow a half an hour just in case).

##### Read in the two files `background.csv` and `records.csv` (see code chunk below)

#### In these two datasets, I simulate a real-world scenario of the sort I dealt with regularly as an institutional data analyst. The `background` dataset contains an ID column that identifies each unique student ($\approx 150,000$ from 2000 to 2018), along with background/demographic variables about each student (the data is fake, but the variables and many features of the data are true-to-life). `fseut` is the first semester a student enrolled at UT; `derivation` is based on a university race/ethnicity/nationality category; `SES` is a measure of socioeconomic status based on educational attainment and family income, averaged for both parents (1=lowest SES category, 10=highest SES category). `AP` and `CBE` indicate transfer credits from those exams. `SAT` is an SAT-equivalent score (ACT converted if applicable).

##### The `records` dataset is a wide file that contains, for each of eight possible years, a unique students' hours undertaken, hours passed, hours failed, grade points, and gpa. You would be wise to familiarize yourself with what these two datasets look like before diving into the assignment, especially `records` (i.e., you will almost certainly save yourself time).

#### 1 (4 pts) How many IDs are in `background` that do not appear in `records`? How many IDs are in `records` that do not appear in `background`? How many IDs do the two datasets have in common? If there were supposed to be 150000 students total, how many students are missing entirely from these data (i.e., their IDs appear neither in the background data or student records)?

```{R}
library(tidyverse)

## On the server? Uncomment and run these

#bg<-read.csv("/stor/work/SDS348_Fall2019/Data/background.csv")
#rec<-read.csv("/stor/work/SDS348_Fall2019/Data/records.csv")

## Not on the server? Uncomment and run these

bg<-read.csv("https://drive.google.com/uc?export=download&id=1iDZjouO3o2KmO3EJg8tdqjKXyQ3XE7FA")
rec<-read.csv("https://drive.google.com/uc?export=download&id=1PhQ51JED5ZVR6Qp85Ds5GK2cg55IQzjr")

#You are encouraged to poke around: to get some sense of the data, try
head(bg)
head(rec)
names(rec)[-1]%>%matrix(nrow=18,byrow=F)

```

```{R}

bg_id <- bg%>%pull(ID)
rec_id <- rec%>%pull(id)

length(setdiff(bg_id,rec_id))
length(setdiff(rec_id,bg_id))

bg_id%>%intersect(rec_id)%>%length()

150000-(bg_id%>%union(rec_id)%>%length())

```

There are 1471 IDs in background that aren't in records, and 2971 IDs in records not in background. The databases have 145,529 IDs in common and there are 29 IDs that don't appear in the background data or student records.

##### 2 (a) (1 pt) Perform a full-join on this data and save it as `fulldata` (1 pt).

```{R}

fulldata <- full_join(bg,rec, by = c("ID"="id"))

head(fulldata)




```

##### 2 (b) (8 pt) Now, tidy this data. Create a new dataset (call it `longdat`). Each student-year-semester is an observation, so I want a column for year order (called `order`: first, second, third, etc.; need to use separate), a column for `semester` (recoded with semester names rather than numbers: "9"="fall", "6"="summer", "2"="spring"; need to use separate), a column called `ccyys` (e.g., 20089, 20092, etc; you will need to create this variable name because it will be NA after separating), and columns for hrs.undertaken, hrs.fail, hrs.pass, grade.points, and gpa. There should be 17 columns total: `ID, fseut, derivation, female, SES, SAT, AP, CBE, graduated, order, semester, ccyys, hrs.undertaken, hrs.fail, hrs.pass, grade.points, gpa`. You will need to use pivot_longer(), separate(), and probably also pivot_wider(). DO NOT PRINT YOUR FINAL OUTPUT: instead, pipe it into `glimpse()`.


```{R}

fulldata %>% pivot_longer(10:153, names_to = "temp1", values_to= "value1") -> longdat

head(longdat)

longdat %>% separate(temp1, sep = "_", into = c("order", "semester", "extra")) -> longdat2

head(longdat2)

longdat2%>%pivot_wider(names_from = "extra", values_from = "value1") -> widedat

widedat%>%mutate(semester=sub("9","fall", semester), semester=sub("6","summer", semester), semester=sub("2","spring", semester)) -> widedat2

widedat2 %>% rename(ccyys="NA") -> widedat3

glimpse(widedat3)

```


##### 3 (a) (1 pt) Take the resulting tidy dataset and remove all rows containing NAs (**use this na-free dataset from here on unless otherwise noted**). How many rows were lost?

```{R}

newdata <- drop_na(widedat3)

nrow(widedat3)-nrow(newdata)



```

6,921 rows were lost.


##### 3 (b) (1 pt) Notice there is no single variable that uniquely identifies a row. Use `unite(...,remove=F)` to add a new variable `unique` that combines `ccyys` and `ID` into a unique identifier. Show that it is in fact unique (i.e., that there are no duplicates in this column).

```{R}

newdata%>%unite(ccyys, ID, col = "unique", remove = F) -> newdata2

glimpse(newdata2)

newdata2 %>% distinct(unique, .keep_all = T) -> distinctdata

glimpse(distinctdata)

nrow(newdata)
nrow(distinctdata)


```

#####  3 (c) (1 pt) Create a new variable called `year` by copying `ccyys` and then removing the fifth digit using `separate()`, or just by using `separate(..., remove=F)` without explicitly copying `ccyys`. The goal is 2008 instead of 20089, 2009 instead of 20092, etc. Keep the last number (9, 2, or 6) around in a column caled semester2 (this variable will make your life easier shortly). Pipe your output into `select(ID,ccyys,year,semester,semester2)%>%glimpse()`

```{R}

newdata2 %>%mutate(year = ccyys) -> newdata3

newdata3 %>% separate("year", into=c("year", "semester2"), sep = 4, convert = T) -> newdata4

newdata4 %>% select(ID,ccyys,year,semester,semester2)%>%glimpse()


```

#####  3 (d) (2 pts) Again, after removing the NAs, create a new column with each student's *cumulative GPA* (call it `cum_gpa`) as of each semester (make sure data is sorted correctly before calculating cumulative statistics). Note that this is not as a simple as averaging the GPAs from each semester (think about an average of averages versus a weighted average). I would probably save this as something else rather than overwriting in case anything goes wrong. Pipe your output into `select(ID,ccyys,gpa,cum_gpa)%>%arrange(ID)%>%glimpse()`

```{R}

newdata4%>%drop_na() -> newdata5

newdata6 <- newdata5%>%group_by(ID)%>% mutate(cum_gpa = cumsum(grade.points)/cumsum(hrs.undertaken))

newdata6


```

##### 3 (e) (1 pt) What proportion of students took at least one summer class? You are advised to use `semester2` rather than `semester` to summarize etc. (it takes much less time).

```{R}

newdata6 %>% select(ID, semester2) %>% filter(semester2 == 6) %>% distinct(ID, .keep_all = T) %>% nrow() -> sumclass

newdata6 %>% distinct(ID) %>% nrow() -> totstud

sumclass/totstud

```

*your answer here, 1-2 sentences*

##### 3 (f) (1 pt) What is the record/maximum for number of semesters attended without graduating? Which student ID has this distinction?
```{R}

newdata6 %>% select(ID, semester, semester2, graduated) %>% filter(graduated == 0) %>% summarise(freq = n()) %>% arrange(desc(freq))


```

*your answer here, 1-2 sentences*

```{R, echo=F}
## DO NOT DELETE THIS BLOCK!
sessionInfo()
Sys.time()
Sys.info()
```